serviceAccount:
  create: false
  annotations: {
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/dev-kstadium-service-eks-all-role-sa
    }
  name: "eks-all-role-sa"

sources:
  - service
  - ingress

policy: upsert-only
registry: txt
txtOwnerId: "Z03689522Y6K96S9DKQ8U"
domainFilters: [dev.kstadium.io]
provider: aws
