apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-application-controller
    namespace: argocd
    resourceVersion: "2640972"
    uid: 339d10a7-2f30-49c0-8478-8422f9081214
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-applicationset-controller
    namespace: argocd
    resourceVersion: "2640977"
    uid: 2cb32afa-18f8-44de-864b-cc53ca53f041
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-dex-server
    namespace: argocd
    resourceVersion: "2640970"
    uid: 429b5d99-c952-487e-ab9c-ecefcc4bdb80
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "2640974"
    uid: 3986a495-09bd-4b53-8e35-b722aaa36d24
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app: argocd-redis-ha
      app.kubernetes.io/managed-by: Helm
      chart: redis-ha-4.23.0
      heritage: Helm
      release: argocd
    name: argocd-redis-ha
    namespace: argocd
    resourceVersion: "2640975"
    uid: 79ea1328-90e9-43ee-8483-681c4dbead5d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app: argocd-redis-ha
      app.kubernetes.io/managed-by: Helm
      chart: redis-ha-4.23.0
      heritage: Helm
      release: argocd
    name: argocd-redis-ha-haproxy
    namespace: argocd
    resourceVersion: "2640976"
    uid: 06a1b9a0-121d-49cb-af63-b77957aad59f
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-repo-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-repo-server
    namespace: argocd
    resourceVersion: "2640973"
    uid: db4a69ba-6d8a-4911-a60e-df45395b6086
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2024-06-03T08:12:40Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.9.1
      helm.sh/chart: argo-cd-5.51.2
    name: argocd-server
    namespace: argocd
    resourceVersion: "2640971"
    uid: f9507cbf-abfa-4304-88ea-ee9ee9cc0815
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-06-03T08:11:52Z"
    name: default
    namespace: argocd
    resourceVersion: "2640797"
    uid: b7a483b7-a9bf-4e49-aa8d-4a3010e181bf
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: default
    namespace: default
    resourceVersion: "334"
    uid: 41c94160-58c5-4767-9679-99ae9d705869
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kbds-jenkins
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-06-18T00:56:32Z"
    labels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: kbds-jenkins
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jenkins
      helm.sh/chart: jenkins-5.2.2
    name: kbds-jenkins
    namespace: default
    resourceVersion: "9136849"
    uid: 569b7493-79d6-4cef-b471-bbad9a330846
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "335"
    uid: 64b3fb40-a621-447d-9094-3b985efcacf1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: default
    namespace: kube-public
    resourceVersion: "336"
    uid: 842af731-fd29-4066-be5e-5ed5ee0c47f9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "261"
    uid: 47ea2f2a-151b-4d5b-959d-d51be34e15d0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:26Z"
    name: aws-cloud-provider
    namespace: kube-system
    resourceVersion: "252"
    uid: 1f3f74e6-7c60-4e03-aa2e-ae9a95be8e32
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::339712708344:role/AmazonEKSLoadBalancerControllerRole
    creationTimestamp: "2024-05-31T07:27:29Z"
    labels:
      app.kubernetes.io/managed-by: eksctl
    name: aws-load-balancer-controller
    namespace: kube-system
    resourceVersion: "1701354"
    uid: f6afdd9e-e004-4254-a16a-5274e2d920cc
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:12:28Z"
    labels:
      app.kubernetes.io/instance: aws-vpc-cni
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: aws-node
      app.kubernetes.io/version: v1.15.1
      helm.sh/chart: aws-vpc-cni-1.15.1
      k8s-app: aws-node
    name: aws-node
    namespace: kube-system
    resourceVersion: "664"
    uid: 65b7715f-8836-4bb3-81e1-a4b3741d8c78
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "265"
    uid: 93a05309-2662-4a06-aaa6-6a5a634582ac
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "319"
    uid: e7deb1ed-329a-4cd7-9a46-75c3f5ec2a68
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:12:27Z"
    labels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
    name: coredns
    namespace: kube-system
    resourceVersion: "627"
    uid: 2077e569-f551-47a7-9b98-2e51af8720b6
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "292"
    uid: 924c6813-a74e-44e3-8be1-a66643967475
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "276"
    uid: b584ddc3-4591-44d2-b858-9fe69697c572
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: default
    namespace: kube-system
    resourceVersion: "342"
    uid: b72b9a1e-456f-419e-8191-d50c35d6613c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "313"
    uid: 55b68e81-7801-4c1c-8410-e9c3ef4729a5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "299"
    uid: 608550d5-0660-4369-bbec-849a60d9dbee
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::339712708344:role/AmazonEKS_EBS_CSI_DriverRole
    creationTimestamp: "2024-05-31T07:13:53Z"
    labels:
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/managed-by: EKS
      app.kubernetes.io/name: aws-ebs-csi-driver
      app.kubernetes.io/version: 1.31.0
    name: ebs-csi-controller-sa
    namespace: kube-system
    resourceVersion: "1698262"
    uid: 5db98d3f-21c1-461f-bab4-a740a5bf1c41
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-31T07:13:54Z"
    labels:
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/managed-by: EKS
      app.kubernetes.io/name: aws-ebs-csi-driver
      app.kubernetes.io/version: 1.31.0
    name: ebs-csi-node-sa
    namespace: kube-system
    resourceVersion: "1698264"
    uid: e23ade52-1d19-42e7-af6f-2b687b0dc999
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"eks-vpc-resource-controller","namespace":"kube-system"}}
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: eks-vpc-resource-controller
    namespace: kube-system
    resourceVersion: "323"
    uid: 9d475f1e-73b7-4e79-be03-111c02cca55d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "269"
    uid: b9008476-906e-475a-af24-a9db29ff7f15
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "306"
    uid: 2cfedec3-ed3d-41ac-9953-3e0487a09bb9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "270"
    uid: 9e793f5e-03ec-461b-9a32-110179846f06
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "303"
    uid: 42d1ac23-8376-4ca7-a4db-8f1c08161539
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "275"
    uid: 3a9ee265-4df1-4191-946b-de816549b13d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "262"
    uid: 574cf9d9-3422-4cba-9bd5-57fd81644562
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "264"
    uid: 27699e9f-68e5-48ee-969f-600aa50c7841
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "263"
    uid: 70792961-04b8-4775-9094-6eace5a85812
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:12:26Z"
    labels:
      eks.amazonaws.com/component: kube-proxy
      k8s-app: kube-proxy
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "617"
    uid: f4ed5391-5bfc-44ad-bf70-f548de9e3241
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "260"
    uid: 5c2a8ff1-cf55-4f41-b9f6-2ab3bb446dab
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:26Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "253"
    uid: 821dd8e1-bf40-4abc-81a9-ec237ce6ead7
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "301"
    uid: 3614f023-0777-41af-a0bc-5f68b92078d2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:31Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "312"
    uid: 5034c034-1119-40a3-b7d4-09eb1ed0f2c6
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "266"
    uid: f0afa213-c729-4e37-b494-75b0cfc50420
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "310"
    uid: f3daa875-d8d5-4ef6-932c-3e542d21f198
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "282"
    uid: dc90d80a-eb16-45e0-bdc9-896ed7c940c5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "272"
    uid: e58b69d7-11dd-4156-bccb-e127fad7f2e1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:27Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "259"
    uid: 0b6138dd-ad71-4f7b-ae6a-fe0d83c5fe1d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "311"
    uid: 0d736067-b8d1-43dc-8bb0-b137c794c9b0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:28Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "273"
    uid: 657fd17e-820f-4cd1-b243-386f42fc844c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:26Z"
    name: service-controller
    namespace: kube-system
    resourceVersion: "254"
    uid: b1f4cafd-1542-4054-b773-a1208f03ac7a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:29Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "274"
    uid: 09ca4dbf-b1cb-47bf-92e5-b384ea2ba593
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:26Z"
    name: tagging-controller
    namespace: kube-system
    resourceVersion: "255"
    uid: 0c8abb79-08eb-4566-a561-111b1909ceec
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "302"
    uid: 3e6e4b01-1f90-4ae9-8024-f5ff8dfdff30
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-05-24T06:10:30Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "308"
    uid: c4bfe65b-5cee-404e-b94b-b1787be36995
kind: List
metadata:
  resourceVersion: ""
