#bases: 
resources:
- ../../../base/develop 
#- ./replica.yaml



namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"

patches:
#- path: ./replica.yaml

commonLabels:
 app: app-admin
commonAnnotations:
 svc: kstadium

images:
#- name: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/develop/test-app-admin
- name: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/develop/default:test
  newName: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/develop/test-app-admin
  newTag: c699385
