Env: stg 
OldTag: kstadium-backend-202401251941 
NewTag: kstadium-backend-202401291123 
AppType: BackEnd
Domain: Kstadium
ARecord: app
CommonSecret:
  App:
    ADMIN_VAULT_PRIVATE_KEY
    GOOGLE_RECAPTCHA_SECRETKEY
    JWT_SECRETKEY
    LAUNCHPAD_OWNER_PRIVATE_KEY
    LOGGING_CONFIG_ACTIVE_ENV
    MEDIUM_API_BASE_URL
    MEDIUM_BESU_ENDPOINT
    MEDIUM_SERVER_CONFIG_CONTRACT_ADDRESS
    MONGO_HOST
    MONGO_PASSWORD
    MONGO_USER
    OCTET_API_BASE_URL
    OCTET_KOK_SYMBOL
    OCTET_SERVICE_URL
    OCTET_MEDIUM_KOK_PRIVATEKEY
    OCTET_MEDIUM_PASSPHRASE
    OCTET_SOP_SYMBOL
    SPRING_DATASOURCE_MYSQL_DB_HOST
    SPRING_DATASOURCE_MYSQL_DB_NAME
    SPRING_DATASOURCE_MYSQL_DB_PORT
    SPRING_DATASOURCE_PASSWORD
    SPRING_DATASOURCE_USERNAME
    SPRING_PROFILES_ACTIVE_ENV
    STADIUM_APP_DOMAIN
    ERC20_TRANSFER_MANAGER_KEY
    ERC20_TRANSFER_CA
    STG_S3_ADMIN_ACCESS_KEY
    STG_S3_ADMIN_SECRET_KEY
    XRP_COLLECTION_WALLET_SEED
CommonSecretSelect: 
  - App
OptionalSecretManagerSelect:
  - Octet
LbConfig: 
  HealthCheck: /kstadium/api/healthcheck
  ListenPorts:
    - protocol: HTTP
      port: 80
    - protocol: HTTPS
      port: 443
    - protocol: HTTPS
      port: 8080
AppSet:
  BackEnd:
    ContainerPort: 8080