prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/load-balancer-name: alb-managed-monitoring
      alb.ingress.kubernetes.io/group.name: managed-monitoring
      alb.ingress.kubernetes.io/group.order: '1'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:911781391110:certificate/c4b1fa44-ad4b-404e-aa4d-6e6e2aa3f858
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /prometheus
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}'
      alb.ingress.kubernetes.io/success-codes: 200-399
      # external-dns.alpha.kubernetes.io/hostname: managed-pm.dev.kstadium.io
    hosts: 
    - monitoring.dev.kstadium.io
    paths: 
    - /prometheus
    pathType: Prefix
  prometheusSpec:
    externalLabels:
      cluster: prometheus-managed
    routePrefix: /prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    # 데이터 유지 및 사이즈
    retention: 10d 
    retionSize: "10Gi"
  serviceAccount:
    create: false
    name: eks-sa-role



alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      # alb.ingress.kubernetes.io/load-balancer-name: alb-managed-monitoring
      alb.ingress.kubernetes.io/group.name: managed-monitoring
      alb.ingress.kubernetes.io/group.order: '2'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:911781391110:certificate/c4b1fa44-ad4b-404e-aa4d-6e6e2aa3f858
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /alertmanager
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}'
      alb.ingress.kubernetes.io/success-codes: 200-399
    hosts: 
    - monitoring.dev.kstadium.io
    paths: 
    - /alertmanager
    pathType: Prefix
  alertmanagerSpec:
    routePrefix: /alertmanager
  serviceAccount:
    create: false
    name: eks-sa-role

grafana:
  defaultDashboardsTimezone: Asia/Seoul
  adminPassword: Devops#@!123
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      # alb.ingress.kubernetes.io/load-balancer-name: alb-managed-monitoring2
      alb.ingress.kubernetes.io/group.name: managed-monitoring
      alb.ingress.kubernetes.io/group.order: '99'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:911781391110:certificate/c4b1fa44-ad4b-404e-aa4d-6e6e2aa3f858
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}'
      alb.ingress.kubernetes.io/success-codes: 200-399
      # external-dns.alpha.kubernetes.io/hostname: managed-gf.dev.kstadium.io
    hosts: 
    - monitoring.dev.kstadium.io
    paths: 
    - /
    pathType: Prefix

prometheusOperator:
  serviceAccount:
    create: false
    name: eks-sa-role

