kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
    name: stg-custom
    region: ap-northeast-2
    annotations:
      cert-manager.io/cluster-issuer: "my-issuer"

vpc:
  id: vpc-<vpc-id>
  cidr: 10.0.0.0/16
  securityGroup: sg-0da577e13607dfa16
  subnets:
    private:
      ap-northeast-2a:
         id: subnet-<private-subnet-a>
      ap-northeast-2b:
         id: subnet-<private-subnet-b>


managedNodeGroups:
  - name: arm # 클러스터의 노드 그룹명
    instanceType: m6g.large # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 2 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    subnets:
      -  subnet-<private-subnet-a>
      -  subnet-<private-subnet-b>
    ssh:
      enableSsm: true
    labels:
      arch: arm64
    taints:
      - key: arch
        value: arm64
        effect: NoSchedule
    iam:
      #  withAddonPolicies:
      #    imageBuilder: true # Amazon ECR에 대한 권한 추가
      #    albIngress: true  # albIngress에 대한 권한 추가
      #    cloudWatch: true # cloudWatch에 대한 권한 추가
      #    autoScaler: true # auto scaling에 대한 권한 추가
      #    ebs: true # EBS CSI Driver에 대한 권한 추가
      instanceRoleARN: arn:aws:iam::123456789012:role/eks-node-role

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
