apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-common-secret
  namespace: kube-system
spec:
  provider: aws

  secretObjects:
    - secretName: dev-common-secret
      type: Opaque
      data:
        - objectName: bridge.DB_DATABASE
          key: bridge.DB_DATABASE
        - objectName: bridge.DB_HOST 
          key: bridge.DB_HOST
        - objectName: bridge.DB_PASSWORD
          key: bridge.DB_PASSWORD
        - objectName: bridge.DB_PORT
          key: bridge.DB_PORT
        - objectName: bridge.DB_USER
          key: bridge.DB_USER
        - objectName: bridge.KAFKA_BROKERS 
          key: bridge.KAFKA_BROKERS
        - objectName: bridge.NODE_ENV
          key: bridge.NODE_ENV
        - objectName: bridge.PORT
          key: bridge.PORT
        - objectName: app.ADMIN_VAULT_PRIVATE_KEY
          key: app.ADMIN_VAULT_PRIVATE_KEY
        - objectName: app.AWS_XRAY_COLLECT_SQL_QUERIES
          key: app.AWS_XRAY_COLLECT_SQL_QUERIES
        - objectName: app.DEV_S3_ADMIN_ACCESS_KEY 
          key: app.DEV_S3_ADMIN_ACCESS_KEY
        - objectName: app.DEV_S3_ADMIN_SECRET_KEY
          key: app.DEV_S3_ADMIN_SECRET_KEY
        - objectName: app.GOOGLE_RECAPTCHA_SECRETKEY
          key: app.GOOGLE_RECAPTCHA_SECRETKEY
        - objectName: app.JWT_SECRETKEY
          key: app.JWT_SECRETKEY
        - objectName: app.LOGGING_CONFIG_ACTIVE_ENV
          key: app.LOGGING_CONFIG_ACTIVE_ENV
        - objectName: app.MEDIUM_API_BASE_URL
          key: app.MEDIUM_API_BASE_URL
        - objectName: app.MEDIUM_BESU_ENDPOINT
          key: app.MEDIUM_BESU_ENDPOINT
        - objectName: app.MEDIUM_SERVER_CONFIG_CONTRACT_ADDRESS
          key: app.MEDIUM_SERVER_CONFIG_CONTRACT_ADDRESS
        - objectName: app.MONGO_HOST
          key: app.MONGO_HOST
        - objectName: app.MONGO_PASSWORD
          key: app.MONGO_PASSWORD
        - objectName: app.MONGO_USER
          key: app.MONGO_USER
        - objectName: app.OCTET_API_BASE_URL
          key: app.OCTET_API_BASE_URL
        - objectName: app.OCTET_API_KEY
          key: app.OCTET_API_KEY
        - objectName: app.OCTET_KOK_SYMBOL
          key: app.OCTET_KOK_SYMBOL
        - objectName: app.OCTET_MEDIUM_KOK_PRIVATEKEY
          key: app.OCTET_MEDIUM_KOK_PRIVATEKEY
        - objectName: app.OCTET_MEDIUM_PASSPHRASE
          key: app.OCTET_MEDIUM_PASSPHRASE
        - objectName: app.OCTET_SOP_SYMBOL
          key: app.OCTET_SOP_SYMBOL
        - objectName: app.SPRING_DATASOURCE_MYSQL_DB_HOST
          key: app.SPRING_DATASOURCE_MYSQL_DB_HOST
        - objectName: app.SPRING_DATASOURCE_MYSQL_DB_NAME
          key: app.SPRING_DATASOURCE_MYSQL_DB_NAME
        - objectName: app.SPRING_DATASOURCE_MYSQL_DB_PORT
          key: app.SPRING_DATASOURCE_MYSQL_DB_PORT
        - objectName: app.SPRING_DATASOURCE_PASSWORD
          key: app.SPRING_DATASOURCE_PASSWORD
        - objectName: app.SPRING_DATASOURCE_USERNAME
          key: app.SPRING_DATASOURCE_USERNAME
        - objectName: app.SPRING_MAIL_PASSWORD
          key: app.SPRING_MAIL_PASSWORD
        - objectName: app.SPRING_MAIL_USERNAME
          key: app.SPRING_MAIL_USERNAME
        - objectName: app.SPRING_PROFILES_ACTIVE_ENV
          key: app.SPRING_PROFILES_ACTIVE_ENV
        - objectName: app.SPRING_REDIS_HOST
          key: app.SPRING_REDIS_HOST
        - objectName: app.SPRING_REDIS_PORT
          key: app.SPRING_REDIS_PORT
        - objectName: app.STADIUM_APP_DOMAIN 
          key: app.STADIUM_APP_DOMAIN                 
  
  parameters:
    region : ap-northeast-2
    objects: |
        - objectName: common-secret
          objectType: "secretsmanager"
          jmesPath:
            - path: bridge.DB_DATABASE
              objectAlias: bridge.DB_DATABASE
            - path: bridge.DB_HOST
              objectAlias: bridge.DB_HOST
            - path: bridge.DB_PASSWORD
              objectAlias: bridge.DB_PASSWORD
            - path: bridge.DB_PORT
              objectAlias: bridge.DB_PORT
            - path: bridge.DB_USER
              objectAlias: bridge.DB_USER
            - path: bridge.KAFKA_BROKERS
              objectAlias: bridge.KAFKA_BROKERS
            - path: bridge.NODE_ENV
              objectAlias: bridge.NODE_ENV
            - path: bridge.PORT
              objectAlias: bridge.PORT  
            - path: app.ADMIN_VAULT_PRIVATE_KEY
              objectAlias: app.ADMIN_VAULT_PRIVATE_KEY
            - path: app.AWS_XRAY_COLLECT_SQL_QUERIES
              objectAlias: app.AWS_XRAY_COLLECT_SQL_QUERIES
            - path: app.DEV_S3_ADMIN_ACCESS_KEY
              objectAlias: app.DEV_S3_ADMIN_ACCESS_KEY
            - path: app.DEV_S3_ADMIN_SECRET_KEY
              objectAlias: app.DEV_S3_ADMIN_SECRET_KEY
            - path: app.GOOGLE_RECAPTCHA_SECRETKEY
              objectAlias: app.GOOGLE_RECAPTCHA_SECRETKEY
            - path: app.JWT_SECRETKEY
              objectAlias: app.JWT_SECRETKEY
            - path: app.LOGGING_CONFIG_ACTIVE_ENV
              objectAlias: app.LOGGING_CONFIG_ACTIVE_ENV
            - path: app.MEDIUM_API_BASE_URL
              objectAlias: app.MEDIUM_API_BASE_URL
            - path: app.MEDIUM_BESU_ENDPOINT
              objectAlias: app.MEDIUM_BESU_ENDPOINT
            - path: app.MEDIUM_SERVER_CONFIG_CONTRACT_ADDRESS
              objectAlias: app.MEDIUM_SERVER_CONFIG_CONTRACT_ADDRESS
            - path: app.MONGO_HOST
              objectAlias: app.MONGO_HOST
            - path: app.MONGO_PASSWORD
              objectAlias: app.MONGO_PASSWORD
            - path: app.MONGO_USER
              objectAlias: app.MONGO_USER
            - path: app.OCTET_API_BASE_URL
              objectAlias: app.OCTET_API_BASE_URL
            - path: app.OCTET_API_KEY
              objectAlias: app.OCTET_API_KEY
            - path: app.OCTET_KOK_SYMBOL
              objectAlias: app.OCTET_KOK_SYMBOL
            - path: app.OCTET_MEDIUM_KOK_PRIVATEKEY
              objectAlias: app.OCTET_MEDIUM_KOK_PRIVATEKEY
            - path: app.OCTET_MEDIUM_PASSPHRASE
              objectAlias: app.OCTET_MEDIUM_PASSPHRASE
            - path: app.OCTET_SOP_SYMBOL
              objectAlias: app.OCTET_SOP_SYMBOL
            - path: app.SPRING_DATASOURCE_MYSQL_DB_HOST
              objectAlias: app.SPRING_DATASOURCE_MYSQL_DB_HOST
            - path: app.SPRING_DATASOURCE_MYSQL_DB_NAME
              objectAlias: app.SPRING_DATASOURCE_MYSQL_DB_NAME
            - path: app.SPRING_DATASOURCE_MYSQL_DB_PORT
              objectAlias: app.SPRING_DATASOURCE_MYSQL_DB_PORT
            - path: app.SPRING_DATASOURCE_PASSWORD
              objectAlias: app.SPRING_DATASOURCE_PASSWORD
            - path: app.SPRING_DATASOURCE_USERNAME
              objectAlias: app.SPRING_DATASOURCE_USERNAME
            - path: app.SPRING_MAIL_PASSWORD
              objectAlias: app.SPRING_MAIL_PASSWORD
            - path: app.SPRING_MAIL_USERNAME
              objectAlias: app.SPRING_MAIL_USERNAME
            - path: app.SPRING_PROFILES_ACTIVE_ENV
              objectAlias: app.SPRING_PROFILES_ACTIVE_ENV
            - path: app.SPRING_REDIS_HOST
              objectAlias: app.SPRING_REDIS_HOST
            - path: app.SPRING_REDIS_PORT
              objectAlias: app.SPRING_REDIS_PORT
            - path: app.STADIUM_APP_DOMAIN
              objectAlias: app.STADIUM_APP_DOMAIN              