apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-common-secret
  namespace: kube-system
spec:
  provider: aws

  secretObjects:
    - secretName: dev-common-secret
      type: Opaque
      data:
        - objectName: bridge.DB.DATABASE
          key: bridge.DB.DATABASE
        - objectName: bridge.DB.HOST 
          key: bridge.DB.HOST
        - objectName: bridge.DB.PASSWORD
          key: bridge.DB.PASSWORD
        - objectName: bridge.DB.PORT
          key: bridge.DB.PORT
        - objectName: bridge.DB.USER
          key: bridge.DB.USER
        - objectName: bridge.KAFKA_BROKERS 
          key: bridge.KAFKA_BROKERS
        - objectName: bridge.NODE_ENV
          key: bridge.NODE_ENV
        - objectName: bridge.PORT
          key: bridge.PORT      
  
  parameters:
    region : ap-northeast-2
    objects: |
        - objectName: "common-secret"
          objectType: "secretsmanager"
          jmesPath:
            - path: bridge.DB.DATABASE
              objectAlias: bridge.DB.DATABASE
            - path: bridge.DB.HOST
              objectAlias: bridge.DB.HOST
            - path: bridge.DB.PASSWORD
              objectAlias: bridge.DB.PASSWORD
            - path: bridge.DB.PORT
              objectAlias: bridge.DB.PORT
            - path: bridge.DB.USER
              objectAlias: bridge.DB.USER
            - path: bridge.KAFKA_BROKERS
              objectAlias: bridge.KAFKA_BROKERS
            - path: bridge.NODE_ENV
              objectAlias: bridge.NODE_ENV
            - path: bridge.PORT
              objectAlias: bridge.PORT