applications: 
- name: example-project-backend
  namespace: managed
  additionalLabels: {}
  additionalAnnotations: {}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  project: default
  source:
    repoURL: git@github.com:example-project/example-project-k8s.git
    targetRevision: develop
    path: manifest/apps/common
    helm:
      valueFiles:
        - common-values.yaml
        - ../example-project-backend/values.yaml
  destination:
    name: dev-example-project-service
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: null

